function gs_dvbs2_stream_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 25.1 (R2025a) at 15:24:58 on 09/10/2025.
% This function was created for the IP Core generated from design 'dvbs2_stream'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x43C00000, ...
	"AddressRange", 0x10000);

DUTPort_TSorGS_In = hdlcoder.DUTPort("TSorGS_In", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,2,0), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_DFL_In = hdlcoder.DUTPort("DFL_In", ...
	"Direction", "IN", ...
	"DataType", "uint16", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

DUTPort_UPL_In = hdlcoder.DUTPort("UPL_In", ...
	"Direction", "IN", ...
	"DataType", "uint16", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x108");

DUTPort_SYNC_In = hdlcoder.DUTPort("SYNC_In", ...
	"Direction", "IN", ...
	"DataType", "uint8", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x10C");

DUTPort_MODCOD_In = hdlcoder.DUTPort("MODCOD_In", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,5,0), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x110");

DUTPort_FECFRAME_In = hdlcoder.DUTPort("FECFRAME_In", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x114");

mapPort(hFPGA, [DUTPort_TSorGS_In, DUTPort_DFL_In, DUTPort_UPL_In, DUTPort_SYNC_In, DUTPort_MODCOD_In, DUTPort_FECFRAME_In]);

%% AXI4-Stream Write
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Write", ...
	"WriteEnable", false, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 32, ...
	"ReadFrameLength", 1024);

DUTPort_AXI4S_Data_Out = hdlcoder.DUTPort("AXI4S_Data_Out", ...
	"Direction", "OUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Write");

mapPort(hFPGA, [DUTPort_AXI4S_Data_Out]);

%% AXI4-Stream Read
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Read", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 32, ...
	"WriteFrameLength", 1024, ...
	"ReadEnable", false);

DUTPort_AXI4S_Data_In = hdlcoder.DUTPort("AXI4S_Data_In", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Read");

mapPort(hFPGA, [DUTPort_AXI4S_Data_In]);

end
