function gs_dvbs2_stream_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 24.2 (R2024b) at 20:15:17 on 24/03/2025.
% This function was created for the IP Core generated from design 'dvbs2_stream'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x43C00000, ...
	"AddressRange", 0x10000);


%% AXI4-Stream Write
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Write", ...
	"WriteEnable", false, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 32, ...
	"ReadFrameLength", 1024);

DUTPort_AXI4S_Data_Out = hdlcoder.DUTPort("AXI4S_Data_Out", ...
	"Direction", "OUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Write");

mapPort(hFPGA, [DUTPort_AXI4S_Data_Out]);

%% AXI4-Stream Read
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Read", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 32, ...
	"WriteFrameLength", 1024, ...
	"ReadEnable", false);

DUTPort_AXI4S_Data_In = hdlcoder.DUTPort("AXI4S_Data_In", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Read");

mapPort(hFPGA, [DUTPort_AXI4S_Data_In]);

end
