function gs_zynqRadioHWSWAXI4StreamAD9361AD9364SL_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 24.2 (R2024b) at 13:40:30 on 14/01/2025.
% This function was created for the IP Core generated from design 'zynqRadioHWSWAXI4StreamAD9361AD9364SL'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x43C00000, ...
	"AddressRange", 0x10000);

DUTPort_maxTxCount = hdlcoder.DUTPort("maxTxCount", ...
	"Direction", "IN", ...
	"DataType", "int16", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_txStart = hdlcoder.DUTPort("txStart", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

DUTPort_txSel = hdlcoder.DUTPort("txSel", ...
	"Direction", "IN", ...
	"DataType", "logical", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x108");

mapPort(hFPGA, [DUTPort_maxTxCount, DUTPort_txStart, DUTPort_txSel]);

%% AXI4-Stream Write
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Write", ...
	"WriteEnable", false, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 32, ...
	"ReadFrameLength", 1024);

DUTPort_AXI4S_Data_Out = hdlcoder.DUTPort("AXI4S_Data_Out", ...
	"Direction", "OUT", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Write");

mapPort(hFPGA, [DUTPort_AXI4S_Data_Out]);

%% AXI4-Stream Read
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream Read", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 32, ...
	"WriteFrameLength", 1024, ...
	"ReadEnable", false);

DUTPort_AXI4S_Data_In = hdlcoder.DUTPort("AXI4S_Data_In", ...
	"Direction", "IN", ...
	"DataType", "int32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Stream Read");

mapPort(hFPGA, [DUTPort_AXI4S_Data_In]);

end
