device_id: 7z020
processor:
    ps7_cortexa9_0:
        arch: aarch64
        ip_name: ps7_cortexa9
        slaves_strings: adc gpio0 intc L2 mc uart1 qspi gem0 sdhci0 slcr dmac_s devcfg global_timer ttc0 scutimer scuwdt usb0 coresight ps7_pmu_0 ps7_ocmc_0 ps7_gpv_0 ps7_scuc_0 ps7_iop_bus_config_0 ps7_dma_ns ps7_afi_0 ps7_afi_1 ps7_afi_2 ps7_afi_3 AXI_GPIO_0
        slaves:
            ps7_qspi_linear_0:
                device_type: linear_flash
                ip_name: ps7_qspi_linear
                baseaddr: '0xfc000000'
                highaddr: '0xfd000000'
            ps7_ddr_0:
                device_type: memory
                ip_name: ps7_ddr
                baseaddr: '0x100000'
                highaddr: '0x20000000'
            ps7_ram_0:
                device_type: memory
                ip_name: ps7_ram
                baseaddr: '0x0'
                highaddr: '0x30000'
            ps7_ram_1:
                device_type: memory
                ip_name: ps7_ram
                baseaddr: '0xffff0000'
                highaddr: '0xfffffe00'
            uart1:
                device_type: serial
                ip_name: ps7_uart
                baseaddr: '0xe0001000'
            gem0:
                device_type: ethernet
                ip_name: ps7_ethernet
            sdhci0:
                device_type: sd
                ip_name: ps7_sdio
            adc:
                ip_name: ps7_xadc
            gpio0:
                ip_name: ps7_gpio
            intc:
                ip_name: ps7_intc_dist
            L2:
                ip_name: ps7_pl310
            mc:
                ip_name: ps7_ddrc
            qspi:
                ip_name: ps7_qspi
            slcr:
                ip_name: ps7_slcr
            dmac_s:
                ip_name: ps7_dma
            devcfg:
                ip_name: ps7_dev_cfg
            global_timer:
                ip_name: ps7_globaltimer
            ttc0:
                ip_name: ps7_ttc
            scutimer:
                ip_name: ps7_scutimer
            scuwdt:
                ip_name: ps7_scuwdt
            usb0:
                ip_name: ps7_usb
            coresight:
                ip_name: ps7_coresight_comp
            ps7_pmu_0:
                ip_name: ps7_pmu
            ps7_ocmc_0:
                ip_name: ps7_ocmc
            ps7_gpv_0:
                ip_name: ps7_gpv
            ps7_scuc_0:
                ip_name: ps7_scuc
            ps7_iop_bus_config_0:
                ip_name: ps7_iop_bus_config
            ps7_dma_ns:
                ip_name: ps7_dma
            ps7_afi_0:
                ip_name: ps7_afi
            ps7_afi_1:
                ip_name: ps7_afi
            ps7_afi_2:
                ip_name: ps7_afi
            ps7_afi_3:
                ip_name: ps7_afi
            AXI_GPIO_0:
                ip_name: axi_gpio
