-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/zynqRadioHWSWAXI4StreamAD9361AD9364SL/HDL_Chirp_ip_src_SR_Latch.vhd
-- Created: 2025-01-14 13:38:16
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_Chirp_ip_src_SR_Latch
-- Source Path: zynqRadioHWSWAXI4StreamAD9361AD9364SL/HDL_DUT/Rx/SR-Latch
-- Hierarchy Level: 2
-- Model version: 10.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_Chirp_ip_src_SR_Latch IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        R                                 :   IN    std_logic;
        S                                 :   IN    std_logic;
        Q                                 :   OUT   std_logic
        );
END HDL_Chirp_ip_src_SR_Latch;


ARCHITECTURE rtl OF HDL_Chirp_ip_src_SR_Latch IS

  -- Signals
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL Unit_Delay_out1                  : std_logic;
  SIGNAL AND_out1                         : std_logic;
  SIGNAL OR_out1                          : std_logic;

BEGIN
  -- SR AND - OR Latch

  NOT_out1 <=  NOT R;

  AND_out1 <= NOT_out1 AND Unit_Delay_out1;

  OR_out1 <= S OR AND_out1;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= OR_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Q <= Unit_Delay_out1;

END rtl;

