-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj/hdlsrc/zynqRadioHWSWAXI4StreamAD9361AD9364SL/HDL_Chirp_ip_src_Detect_Change.vhd
-- Created: 2025-01-14 13:38:16
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDL_Chirp_ip_src_Detect_Change
-- Source Path: zynqRadioHWSWAXI4StreamAD9361AD9364SL/HDL_DUT/Tx/Detect Change
-- Hierarchy Level: 2
-- Model version: 10.0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDL_Chirp_ip_src_Detect_Change IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        U                                 :   IN    std_logic;
        Y                                 :   OUT   std_logic
        );
END HDL_Chirp_ip_src_Detect_Change;


ARCHITECTURE rtl OF HDL_Chirp_ip_src_Detect_Change IS

  -- Signals
  SIGNAL U_k_1                            : std_logic;
  SIGNAL FixPt_Relational_Operator_out1   : std_logic;

BEGIN
  -- Edge
  -- U(k)

  -- 
  -- Store in Global RAM
  Delay_Input1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      U_k_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        U_k_1 <= U;
      END IF;
    END IF;
  END PROCESS Delay_Input1_process;


  
  FixPt_Relational_Operator_out1 <= '1' WHEN U /= U_k_1 ELSE
      '0';

  Y <= FixPt_Relational_Operator_out1;

END rtl;

